name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: fmt
        run: cargo fmt -- --check
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: test (debug)
        run: cargo test
      - name: test (release)
        run: cargo test --release
      - name: doctest
        run: cargo test --doc
